import { makeNode } from './node-factory'
import type { CanvasDocument } from './types'

const initialNodes = [
  makeNode({
    id: 'desktop-frame',
    name: 'Northwind — Desktop',
    kind: 'frame',
    parentId: null,
    x: 140,
    y: 120,
    width: 1120,
    height: 760,
    style: { background: '#f3efe6', borderColor: '#d8d1c5', borderWidth: 1 },
  }),
  makeNode({
    id: 'desktop-brand',
    name: 'Wordmark',
    kind: 'text',
    parentId: 'desktop-frame',
    x: 58,
    y: 42,
    width: 178,
    height: 28,
    content: 'NORTHWIND',
    style: {
      color: '#171815',
      fontFamily: 'sans',
      fontSize: 15,
      fontWeight: 760,
      letterSpacing: 2.6,
    },
  }),
  makeNode({
    id: 'desktop-nav-one',
    name: 'Nav / Collection',
    kind: 'text',
    parentId: 'desktop-frame',
    x: 742,
    y: 45,
    width: 92,
    height: 22,
    content: 'Collection',
    style: {
      color: '#5c5c54',
      fontFamily: 'sans',
      fontSize: 13,
      fontWeight: 540,
    },
  }),
  makeNode({
    id: 'desktop-nav-two',
    name: 'Nav / Journal',
    kind: 'text',
    parentId: 'desktop-frame',
    x: 858,
    y: 45,
    width: 72,
    height: 22,
    content: 'Journal',
    style: {
      color: '#5c5c54',
      fontFamily: 'sans',
      fontSize: 13,
      fontWeight: 540,
    },
  }),
  makeNode({
    id: 'desktop-nav-bag',
    name: 'Nav / Bag',
    kind: 'badge',
    parentId: 'desktop-frame',
    x: 974,
    y: 34,
    width: 88,
    height: 40,
    content: 'Bag · 02',
    style: {
      background: '#171815',
      color: '#f7f2e8',
      radius: 999,
      fontFamily: 'sans',
      fontSize: 12,
      fontWeight: 650,
    },
  }),
  makeNode({
    id: 'desktop-kicker',
    name: 'Eyebrow',
    kind: 'text',
    parentId: 'desktop-frame',
    x: 60,
    y: 154,
    width: 260,
    height: 20,
    content: 'OBJECTS / 2026 EDITION',
    style: {
      color: '#d94f2b',
      fontFamily: 'mono',
      fontSize: 11,
      fontWeight: 600,
      letterSpacing: 1.4,
    },
  }),
  makeNode({
    id: 'desktop-title',
    name: 'Hero heading',
    kind: 'text',
    parentId: 'desktop-frame',
    x: 56,
    y: 190,
    width: 520,
    height: 192,
    content: 'Objects for\nslower mornings.',
    style: {
      color: '#171815',
      fontFamily: 'display',
      fontSize: 72,
      fontWeight: 440,
      letterSpacing: -2.8,
      lineHeight: 0.94,
    },
  }),
  makeNode({
    id: 'desktop-copy',
    name: 'Hero body',
    kind: 'text',
    parentId: 'desktop-frame',
    x: 61,
    y: 426,
    width: 392,
    height: 74,
    content:
      'A considered collection of tactile forms, made in small batches for the rituals that make a day yours.',
    style: {
      color: '#68675f',
      fontFamily: 'sans',
      fontSize: 16,
      fontWeight: 430,
      lineHeight: 1.5,
    },
  }),
  makeNode({
    id: 'desktop-cta',
    name: 'Primary action',
    kind: 'button',
    parentId: 'desktop-frame',
    x: 60,
    y: 546,
    width: 184,
    height: 52,
    content: 'Explore the edit  ↗',
    style: {
      background: '#e95c35',
      color: '#fffaf1',
      radius: 3,
      fontFamily: 'sans',
      fontSize: 13,
      fontWeight: 720,
    },
  }),
  makeNode({
    id: 'desktop-note',
    name: 'Edition note',
    kind: 'text',
    parentId: 'desktop-frame',
    x: 60,
    y: 679,
    width: 330,
    height: 22,
    content: 'FREE DELIVERY · 30 DAY RETURNS',
    style: {
      color: '#8f8c82',
      fontFamily: 'mono',
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: 1,
    },
  }),
  makeNode({
    id: 'desktop-image',
    name: 'Hero still life',
    kind: 'image',
    parentId: 'desktop-frame',
    x: 615,
    y: 110,
    width: 447,
    height: 578,
    asset: 'ceramic',
    style: {
      background: '#d4c6b3',
      radius: 224,
      shadow: '0 22px 80px rgba(57, 44, 29, .16)',
    },
  }),
  makeNode({
    id: 'desktop-image-label',
    name: 'Image annotation',
    kind: 'badge',
    parentId: 'desktop-frame',
    x: 880,
    y: 640,
    width: 142,
    height: 34,
    content: 'NO. 04 / ASH',
    style: {
      background: 'rgba(247, 242, 232, .88)',
      color: '#262722',
      radius: 999,
      fontFamily: 'mono',
      fontSize: 10,
      fontWeight: 600,
    },
  }),
  makeNode({
    id: 'mobile-frame',
    name: 'Northwind — Mobile',
    kind: 'frame',
    parentId: null,
    x: 1360,
    y: 170,
    width: 390,
    height: 844,
    style: {
      background: '#171815',
      borderColor: '#343630',
      borderWidth: 1,
      radius: 24,
    },
  }),
  makeNode({
    id: 'mobile-brand',
    name: 'Mobile wordmark',
    kind: 'text',
    parentId: 'mobile-frame',
    x: 28,
    y: 34,
    width: 150,
    height: 22,
    content: 'NORTHWIND',
    style: {
      color: '#f6f0e6',
      fontFamily: 'sans',
      fontSize: 13,
      fontWeight: 760,
      letterSpacing: 2.2,
    },
  }),
  makeNode({
    id: 'mobile-menu',
    name: 'Menu chip',
    kind: 'badge',
    parentId: 'mobile-frame',
    x: 304,
    y: 24,
    width: 58,
    height: 38,
    content: 'MENU',
    style: {
      background: '#f0eadf',
      color: '#171815',
      radius: 999,
      fontFamily: 'mono',
      fontSize: 9,
      fontWeight: 600,
    },
  }),
  makeNode({
    id: 'mobile-image',
    name: 'Mobile product image',
    kind: 'image',
    parentId: 'mobile-frame',
    x: 24,
    y: 96,
    width: 342,
    height: 430,
    asset: 'portrait',
    style: { background: '#796e5d', radius: 171 },
  }),
  makeNode({
    id: 'mobile-kicker',
    name: 'Mobile eyebrow',
    kind: 'text',
    parentId: 'mobile-frame',
    x: 28,
    y: 568,
    width: 260,
    height: 18,
    content: 'THE MORNING EDIT / 04',
    style: {
      color: '#f07a55',
      fontFamily: 'mono',
      fontSize: 9,
      fontWeight: 600,
      letterSpacing: 1.2,
    },
  }),
  makeNode({
    id: 'mobile-title',
    name: 'Mobile heading',
    kind: 'text',
    parentId: 'mobile-frame',
    x: 25,
    y: 606,
    width: 334,
    height: 112,
    content: 'Form follows\nfeeling.',
    style: {
      color: '#f4eee4',
      fontFamily: 'display',
      fontSize: 48,
      fontWeight: 440,
      letterSpacing: -1.8,
      lineHeight: 0.94,
    },
  }),
  makeNode({
    id: 'mobile-cta',
    name: 'Mobile action',
    kind: 'button',
    parentId: 'mobile-frame',
    x: 26,
    y: 758,
    width: 338,
    height: 56,
    content: 'View the collection',
    style: {
      background: '#f0eadf',
      color: '#171815',
      radius: 4,
      fontFamily: 'sans',
      fontSize: 13,
      fontWeight: 720,
    },
  }),
  makeNode({
    id: 'system-frame',
    name: 'Material system',
    kind: 'frame',
    parentId: null,
    x: 180,
    y: 1040,
    width: 1080,
    height: 480,
    style: { background: '#111310', borderColor: '#2b2e28', borderWidth: 1 },
  }),
  makeNode({
    id: 'system-label',
    name: 'System label',
    kind: 'text',
    parentId: 'system-frame',
    x: 48,
    y: 40,
    width: 280,
    height: 22,
    content: 'MATERIAL SYSTEM / 001',
    style: {
      color: '#7f8377',
      fontFamily: 'mono',
      fontSize: 10,
      fontWeight: 500,
      letterSpacing: 1.3,
    },
  }),
  makeNode({
    id: 'system-title',
    name: 'System title',
    kind: 'text',
    parentId: 'system-frame',
    x: 46,
    y: 96,
    width: 390,
    height: 96,
    content: 'Quiet utility.\nWarm precision.',
    style: {
      color: '#f3ede3',
      fontFamily: 'display',
      fontSize: 42,
      fontWeight: 430,
      letterSpacing: -1.3,
      lineHeight: 1,
    },
  }),
  makeNode({
    id: 'swatch-one',
    name: 'Swatch / Bone',
    kind: 'shape',
    parentId: 'system-frame',
    x: 492,
    y: 42,
    width: 152,
    height: 168,
    style: { background: '#f3efe6', radius: 3 },
  }),
  makeNode({
    id: 'swatch-two',
    name: 'Swatch / Clay',
    kind: 'shape',
    parentId: 'system-frame',
    x: 668,
    y: 42,
    width: 152,
    height: 168,
    style: { background: '#e95c35', radius: 3 },
  }),
  makeNode({
    id: 'swatch-three',
    name: 'Swatch / Moss',
    kind: 'shape',
    parentId: 'system-frame',
    x: 844,
    y: 42,
    width: 188,
    height: 168,
    style: { background: '#a9b276', radius: 3 },
  }),
  makeNode({
    id: 'system-card',
    name: 'Feature card',
    kind: 'shape',
    parentId: 'system-frame',
    x: 48,
    y: 264,
    width: 984,
    height: 166,
    style: {
      background: '#1b1e19',
      borderColor: '#34382f',
      borderWidth: 1,
      radius: 6,
    },
  }),
  makeNode({
    id: 'system-card-number',
    name: 'Feature number',
    kind: 'text',
    parentId: 'system-frame',
    x: 76,
    y: 294,
    width: 100,
    height: 22,
    content: '01 — 04',
    style: {
      color: '#e95c35',
      fontFamily: 'mono',
      fontSize: 10,
      fontWeight: 600,
    },
  }),
  makeNode({
    id: 'system-card-title',
    name: 'Feature heading',
    kind: 'text',
    parentId: 'system-frame',
    x: 76,
    y: 336,
    width: 360,
    height: 52,
    content: 'Built to be handled.',
    style: {
      color: '#f3ede3',
      fontFamily: 'display',
      fontSize: 30,
      fontWeight: 440,
    },
  }),
  makeNode({
    id: 'system-card-copy',
    name: 'Feature copy',
    kind: 'text',
    parentId: 'system-frame',
    x: 540,
    y: 310,
    width: 428,
    height: 72,
    content:
      'Every object begins with the hand: weight, balance, texture, and the small evidence of how it was made.',
    style: {
      color: '#a7aa9f',
      fontFamily: 'sans',
      fontSize: 14,
      fontWeight: 430,
      lineHeight: 1.55,
    },
  }),
]

export const initialDocument: CanvasDocument = {
  id: 'demo',
  title: 'Northwind launch',
  nodes: Object.fromEntries(initialNodes.map((node) => [node.id, node])),
  order: initialNodes.map((node) => node.id),
}
